// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjaiIc4Ictl8z0emaYHh3RC4HF5R5IpQ8',
    appId: '1:1033012440984:web:0b7f585c404225f2bac5ed',
    messagingSenderId: '1033012440984',
    projectId: 'revision-cc299',
    authDomain: 'revision-cc299.firebaseapp.com',
    databaseURL: 'https://revision-cc299-default-rtdb.firebaseio.com',
    storageBucket: 'revision-cc299.firebasestorage.app',
    measurementId: 'G-HKDFFPTQVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS1EnvBiqdm9EDHtbvRGQMaxVFYtCfXF0',
    appId: '1:1033012440984:android:085ab76b2c192c23bac5ed',
    messagingSenderId: '1033012440984',
    projectId: 'revision-cc299',
    databaseURL: 'https://revision-cc299-default-rtdb.firebaseio.com',
    storageBucket: 'revision-cc299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLcNsM7Q55THTResNKCbAKJzMncxY0YGk',
    appId: '1:1033012440984:ios:c3fa6226d3ca36f5bac5ed',
    messagingSenderId: '1033012440984',
    projectId: 'revision-cc299',
    databaseURL: 'https://revision-cc299-default-rtdb.firebaseio.com',
    storageBucket: 'revision-cc299.firebasestorage.app',
    androidClientId: '1033012440984-fghb8688rn125epeme7uqjcdi5bofqlt.apps.googleusercontent.com',
    iosClientId: '1033012440984-qimuaqc82vnpu9kbog5tdedsgqss4rbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.allImplementProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLcNsM7Q55THTResNKCbAKJzMncxY0YGk',
    appId: '1:1033012440984:ios:c3fa6226d3ca36f5bac5ed',
    messagingSenderId: '1033012440984',
    projectId: 'revision-cc299',
    databaseURL: 'https://revision-cc299-default-rtdb.firebaseio.com',
    storageBucket: 'revision-cc299.firebasestorage.app',
    androidClientId: '1033012440984-fghb8688rn125epeme7uqjcdi5bofqlt.apps.googleusercontent.com',
    iosClientId: '1033012440984-qimuaqc82vnpu9kbog5tdedsgqss4rbc.apps.googleusercontent.com',
    iosBundleId: 'com.example.allImplementProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjaiIc4Ictl8z0emaYHh3RC4HF5R5IpQ8',
    appId: '1:1033012440984:web:dabed46aa489f179bac5ed',
    messagingSenderId: '1033012440984',
    projectId: 'revision-cc299',
    authDomain: 'revision-cc299.firebaseapp.com',
    databaseURL: 'https://revision-cc299-default-rtdb.firebaseio.com',
    storageBucket: 'revision-cc299.firebasestorage.app',
    measurementId: 'G-R0466F0WVN',
  );

}