// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuHJWySRPGYy4NwXnQJxZ6E9SWayeiVPk',
    appId: '1:718513063854:web:56718a30c6009c28c26a3f',
    messagingSenderId: '718513063854',
    projectId: 'doworkdeleteit',
    authDomain: 'doworkdeleteit.firebaseapp.com',
    storageBucket: 'doworkdeleteit.firebasestorage.app',
    measurementId: 'G-M9PDXJF956',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ-cp6kWKXYQW08Ecn4rRGrdTSMlTXbSI',
    appId: '1:718513063854:android:4923e8d90996554ac26a3f',
    messagingSenderId: '718513063854',
    projectId: 'doworkdeleteit',
    storageBucket: 'doworkdeleteit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJbNZr12pbUoHsFe1zZblE0Yh-Rj3Q62c',
    appId: '1:718513063854:ios:97e9f1c6bcf1de5cc26a3f',
    messagingSenderId: '718513063854',
    projectId: 'doworkdeleteit',
    storageBucket: 'doworkdeleteit.firebasestorage.app',
    androidClientId: '718513063854-1ulculacc8i5fj3328vfmp3dh0rn5o45.apps.googleusercontent.com',
    iosClientId: '718513063854-jfiia0qmecj0evmsapqk5dd6dlcnp32o.apps.googleusercontent.com',
    iosBundleId: 'com.example.allImplementProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJbNZr12pbUoHsFe1zZblE0Yh-Rj3Q62c',
    appId: '1:718513063854:ios:97e9f1c6bcf1de5cc26a3f',
    messagingSenderId: '718513063854',
    projectId: 'doworkdeleteit',
    storageBucket: 'doworkdeleteit.firebasestorage.app',
    androidClientId: '718513063854-1ulculacc8i5fj3328vfmp3dh0rn5o45.apps.googleusercontent.com',
    iosClientId: '718513063854-jfiia0qmecj0evmsapqk5dd6dlcnp32o.apps.googleusercontent.com',
    iosBundleId: 'com.example.allImplementProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuHJWySRPGYy4NwXnQJxZ6E9SWayeiVPk',
    appId: '1:718513063854:web:8da64033a635ae11c26a3f',
    messagingSenderId: '718513063854',
    projectId: 'doworkdeleteit',
    authDomain: 'doworkdeleteit.firebaseapp.com',
    storageBucket: 'doworkdeleteit.firebasestorage.app',
    measurementId: 'G-7JLEJZWLME',
  );
}
